language: generic
sudo: required
services: 
  - docker
before-install: 
  - docker build -t nipunsinha/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true nipunsinha/docker-react npm run test
